version: "3.9"

services:
  empleados-db:
    image: postgres:16
    container_name: reclutamiento_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reclutamiento
    ports:
      - "5433:5432"
    volumes:
      - reclutamiento_data:/var/lib/postgresql/data

volumes:
  reclutamiento_data:
