version: "3.9"

services:
  empleados-db:
    image: postgres:16
    container_name: empleados_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: empleados
    ports:
      - "5433:5432"
    volumes:
      - empleados_data:/var/lib/postgresql/data

volumes:
  empleados_data:
